development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: heroku_mysql_development
  pool: 5
  username: 
  password:
  # socket: /tmp/mysql.sock
test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: heroku_mysql_development
  pool: 5
  username: 
  password:
  # socket: /tmp/mysql.sock

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: heroku_mysql_development
  pool: 5
  username: 
  password:
  # socket: /tmp/mysql.sock
